<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'google_id',
        'password',
        'role',
        'department',
        'title',
        'avatar_url',
        'is_active',
        'subscription_plan',
        'subscription_status',
        'billing_interval',
        'seats_count',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
            'seats_count' => 'integer',
        ];
    }

    /**
     * Orders and billing transactions.
     */
    public function orders(): HasMany
    {
        return $this->hasMany(Order::class)->latest();
    }

    /**
     * Tasks assigned to this user.
     */
    public function assignedTasks(): HasMany
    {
        return $this->hasMany(Task::class, 'assigned_to');
    }

    /**
     * Tasks created by this user.
     */
    public function createdTasks(): HasMany
    {
        return $this->hasMany(Task::class, 'created_by');
    }

    /**
     * Workflows owned by this user.
     */
    public function ownedWorkflows(): HasMany
    {
        return $this->hasMany(Workflow::class, 'owner_id');
    }

    /**
     * Activity records generated by this user.
     */
    public function activities(): HasMany
    {
        return $this->hasMany(TaskActivity::class, 'user_id');
    }

    /**
     * Check if user is a super administrator.
     */
    public function isSuperAdmin(): bool
    {
        return $this->role === 'super_admin';
    }

    /**
     * Check if user is an administrator.
     */
    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    /**
     * Check if user is an operations manager.
     */
    public function isManager(): bool
    {
        return $this->role === 'manager';
    }

    /**
     * Check if user is an operator.
     */
    public function isOperator(): bool
    {
        return $this->role === 'operator';
    }

    /**
     * Check if user is a member.
     */
    public function isMember(): bool
    {
        return $this->role === 'member';
    }

    /**
     * Check if user has management permissions (admin or manager).
     */
    public function canManageWorkflows(): bool
    {
        return in_array($this->role, ['super_admin', 'admin', 'manager'], true);
    }

    /**
     * Human-friendly subscription plan name.
     */
    public function getPlanLabelAttribute(): string
    {
        return match ($this->subscription_plan) {
            'intelligence' => 'Enterprise Intelligence (NVIDIA Engine)',
            'sovereign' => 'Air-Gapped Sovereign',
            'free' => 'Free Trial',
            default => 'Operations Core',
        };
    }

    /**
     * Get avatar image URL or fallback to UI avatars.
     */
    public function getAvatarAttribute(): string
    {
        if ($this->avatar_url) {
            return $this->avatar_url;
        }

        $name = urlencode($this->name);

        return "https://ui-avatars.com/api/?name={$name}&color=4f46e5&background=e0e7ff&bold=true";
    }
}
